### ISSUE TITLE
Clicking step back button freezes MARIE.js

### ISSUE THREAD

**Issue by jos0003** [MARIE-js/MARIE.js#163]
Clicking the step back button causes MARIE.js to freeze for some reason.

**Comment by lorderikir** [comment]
@jos0003 - Doesn't freeze for me

**Comment by lorderikir** [comment]
As bug doesn't freeze, this issue has been depreciated

**Comment by jos0003** [comment]
I've replicated the issue:

1. Assemble and run this code. It should give a runtime error.
```
JumpI X
X, DEC 4098
```

2. Click restart

3. Click microstep button once

4. Click step button twice
