### ISSUE TITLE
[Public][Feedback Form] Themes

### ISSUE THREAD

**Issue by lorderikir** [MARIE-js/MARIE.js#191]
- Have have a dark mode.

**Comment by atrotors** [comment]
amen

**Comment by lorderikir** [comment]
This can be done by changing css files. Also CodeMirror also has themes, we can set the preferences in localstorage

**Comment by lorderikir** [comment]
Initial Implementation of Light and Dark themes in following pull requests
#202 and #201

**Comment by lorderikir** [comment]
Almost ready for production, all we need to do is to fix the bug when it initially loads the preferences on a blank localstorage value

**Comment by atrotors** [comment]
I'm re-opening this because I feel like the night mode isn't truly night mode.
The editor is still light and needs to be dark as well. Same applies to RTL, output and watch list tabs.

**Comment by atrotors** [comment]
It looks good after #213
