### ISSUE TITLE
Error in JUMPI instruction in Wiki RTL page

### ISSUE THREAD

**Issue by EvansMatthew97** [MARIE-js/MARIE.js#276]
On the page https://github.com/MARIE-js/MARIE.js/wiki/Register-Transfer-Language, it states the following for STORE:

**JumpI X** uses the value at X as the address to jump to
```
MAR ← X             # loads value X into MAR
MBR ← M[MAR]        # loads value stored at address X into MBR
MAR ← MBR           # loads value back into MAR
MBR ← M[MAR]        # fetches the value at the address into MBR
PC  ← MBR           # loads the value into PC
```

This should be 
```
MAR ← X             # loads value X into MAR
MBR ← M[MAR]        # loads value stored at address X into MBR
PC  ← MBR           # loads the value into PC
```

by the logic that a simple jump is as follows:
**Jump X** jumps to address X

```
PC ← X
```

**Comment by lorderikir** [comment]
Hi @EvansMatthew97, thanks for submitting this issue. 

The wiki has been updated with the change.
