### ISSUE TITLE
Multiplication example does not work as expected in the marie.js simulator.

### ISSUE THREAD

**Issue by kishorliv** [MARIE-js/MARIE.js#286]
The multiplication example is [here](https://marie.js.org/?multiply).
The example takes value contained in Y as a counter for the loop, decreases it by 1 untill the counter reaches 0.
```
         Load Y
         Subt one
         Store Y
```
The multiplication fails when value in Y is negative. The loop becomes infinite.
So, -3 * 5 works. 5 * -3 doesn't!

The page for this example is removed.The link is [here](https://github.com/MARIE-js/MARIE.js/wiki/Multiplication-in-MARIE). 
I opened a pull request for this issue [here](https://github.com/MARIE-js/MARIE.js/pull/287).

**Comment by auroranil** [comment]
Good work! I have tidied up the code, and also handled the case where Y = 0, in which case outputs 0. Closing this issue.
