### ISSUE TITLE
Unicode Output (UTF-16) is not handled correctly

### ISSUE THREAD

**Issue by jhannemann** [MARIE-js/MARIE.js#288]
#When set to UNICODE, the output log uses the JS [String.fromCharCode(value)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/fromCharCode) function.
This only works correctly for the Base Multilingual Plane (BMP). It would be cool to be able to output a surrogate pair (e.g a sequence of 2 words/4 bytes) to represent emojis such as [this one](https://www.iemoji.com/view/emoji/1112/smileys-people/slightly-smiling-face)  &#x1f642; (UTF-16 encoding d83dde42). Alternatively, UTF-8 would be even cooler, as it's more widely used. The benefit would be to demonstrate to students how multi-byte encodings work. Null-Lobur is terribly behind in terms of Unicode (basically saying that UCS-2 is still a thing).
In any case, even if you think this is not worth doing, please make sure that students understand that Unicode in this case means Unicode in the UTF-16 encoding, e.g. by labeling the output mode drop-down as Unicode (UTF-16).
See pull request #291

**Comment by auroranil** [comment]
Pull request #291 resolves this issue. I have bumped version to `v1.3.0`, and deployed changes to `gh-pages` branch.

**Comment by jhannemann** [comment]
Thanks for accepting the pull request. Next up, I'll have a look at the input. This is a bit more complex, but I may have an idea on how to handle this.

Let me commend you on the high quality of the code. It was really easy to find the exact point to add my changes to, and there were no unexpected side effects. The whole code review process by you guys was just exemplary and outstanding. I'll definitely use this example in my upcoming computer organization class.
