### ISSUE TITLE
Mixed up opcodes in Instruction Set Wiki

### ISSUE THREAD

**Issue by jiaminglimjm** [MARIE-js/MARIE.js#302]
The hex opcodes for `StoreI` and `LoadI` in the [MARIE Instruction Set Wiki](https://github.com/MARIE-js/MARIE.js/wiki/MARIE-Instruction-Set-(with-Opcodes)) are flipped. They are actually `E` and `D` respectively.

https://github.com/MARIE-js/MARIE.js/blob/1c3e54871d689c485a7bb7fffadd74f145292fa5/src/js/marie.js#L668-L669
https://github.com/MARIE-js/MARIE.js/blob/1c3e54871d689c485a7bb7fffadd74f145292fa5/src/js/marie.js#L648-L649

**Comment by auroranil** [comment]
https://github.com/MARIE-js/MARIE.js/wiki/MARIE-Instruction-Set-(with-Opcodes)/_compare/a8032f1a8db2fc175f7c5fda115b1aab3be8aaaf...16b245a17021e1735c8d55467e28e61e12a143ab

Documentation is now consistent with source code for MARIE.js.
