### ISSUE TITLE
Make the site more responsive

### ISSUE THREAD

**Issue by jos0003** [MARIE-js/MARIE.js#35]
The user interface for the site should display without any hiccups for a variety of screen sizes.

Specifically, we should:
* scale CodeMirror and tabs upwards for high resolution displays (especially 4k monitors)
* collapse the nav and action bar for small screens somehow, showing only critical features (but still allowing users to perform intermediary clicks to reach all features of MARIE.js)
* hide "View on GitHub" button on small screens (may also want to add a link to this GitHub repository in the nav bar under "Help")
* implement this for the dropdown menus in the nav bar: http://bjk5.com/post/44698559168/breaking-down-amazons-mega-dropdown
* As the page is being loaded, it should keep layout changes to a minimum

**Comment by lorderikir** [comment]
Use this: https://github.com/kamens/jQuery-menu-aim

CSS Code could change to something like this:

`
.flex{
   //previous code
  height: 80%
  padding: inherit;
}
`

**Comment by cyderize** [comment]
I have some plans to redo the layout to work better regardless of screen resolution, but I'll probably have to try it out and see whether it's actually possible (and also experiment with flexbox polyfills for IE)

**Comment by lorderikir** [comment]
Yeah @cyderize. The screen resolution should have a higher priority then the menu system currently. I think we should leave the menu for now and introduce the menu-system that @jos0003 mentioned in v1.0

**Comment by lorderikir** [comment]
Fixed in v0.5.0
