### ISSUE TITLE
CodeMirror for mobile/tablet devices doesn't work properly

### ISSUE THREAD

**Issue by jos0003** [MARIE-js/MARIE.js#36]
Weird line number glitches and text duplication makes MARIE.js practically unusable for mobile/tablet devices. We may either need to patch CodeMirror to fix this bug, or resort to a different web text editor library that handles input perfectly for mobile/tablet users.

**Comment by lorderikir** [comment]
This currently affects all mobile web browsers and Safari on OS X Devices. Seems that these web browsers don't support generators.

Following are test results to isolate the problem.

> **Successful:** OSX Firefox
> **Unsuccessful:** OSX Safari, iOS Safari/Chrome, Anrdoid Chrome/Firefox/Stock

**Comment by cyderize** [comment]
What does support for generators have to do with this?

Only the MARIE simulator uses generators, and we use transpilation to ES5 now, so that shouldn't be an issue anymore. CodeMirror certainly doesn't make use of generators.

**Comment by lorderikir** [comment]
For Safari it might be WebKit that is screwing up.

**Comment by lorderikir** [comment]
>Modern mobile browsers tend to partly work. Bug reports and patches for mobile support are welcome, but the maintainer does not have the time or budget to actually work on it himself.

**Comment by lorderikir** [comment]
`
var android_spacer = $('<div/>', {
    'class' : 'android_spacer'
}).css({
    'width'  : '100%',
    'height' :  '200px'
}).appendTo($('#parent_view'));

$('#the_textarea').on('focus', function() {
    $(this).after(android_spacer);
});

$('#the_textarea').on('blur', function() {
    $('.android_spacer').remove();
});
`

Code which FaceBook Implements to fix `<textarea>` in mobile browsers.

**Comment by lorderikir** [comment]
Other alternatives include:

- http://www.cdolivet.com/editarea/ (example: http://www.cdolivet.com/editarea/editarea/exemples/exemple_full.html)
- http://www.ymacs.org/
- ACE UI

Source: http://blog.dreamcss.com/wysiwyg-editor/javascript-source-code-editors/

**Comment by lorderikir** [comment]
Attempt to update CodeMirror to latest version again to see if bug is fixed/

**Comment by lorderikir** [comment]
Latest update to patch v0.4.4 fixes some issues with mobile device(s) for android. Need to test with iOS devices.

**Comment by lorderikir** [comment]
This is affected by the IME Bug within CodeMirror. Developers of CodeMirror will eventually do a major overhaul of IME in CodeMIrror. Latest Versions have fixed many issues but the backspace issue is still a problem [Codemirror #3530](https://github.com/codemirror/CodeMirror/issues/3530#event-666890815)

**Comment by MattQlik** [comment]
Not sure if this needs a separate issue opened but if you type a word in Chinese pinyin IME (e.g. zuqiu 足球) on Chrome on a Samsung Galaxy S2 Tab (Android 5.1.1) then change back to English keyboard and delete the word you just typed, the next word you type in English will behave as if it's in IME mode, i.e. the current text is underlined as you type and then when you press Space the word is committed but the cursor is next to the last letter so you need to press Space again to get an actual space between your words. If word wrapping is implemented on the text area that you're using then it is even more weird as the text you type in English will initially be displayed vertically, only changing to horizontal when you press Space.

**Comment by lorderikir** [comment]
**Tested on:** Chrome on Android v6.0.1 (Samsung Galaxy Tab S2)

***
Latest commit fixed some major issues with IME, though there are a few problems such as:

- line numbering not showing up properly
- autocomplete.js may have problems in these browsers

**Comment by zcyzcy88** [comment]
Orion editor works on touch screen well (because Orion editor is directly use `contenteditable`, not simulate everything)
