### ISSUE TITLE
Tutorials Page (wiki?)

### ISSUE THREAD

**Issue by lorderikir** [MARIE-js/MARIE.js#39]
> we can also work on tutorials (but please don't go overboard on this - keep it minimal)

This can be done by: 
- adding new html page
- using Wiki page on MARIE.js

**Comment by jos0003** [comment]
We can reuse `bootstrap-popover-x` to show users a "tour" on how to use MARIE.js. 

The tour option should show up for the first time (with a confirmation box if the user wants to view the tour), then never show up again in future page visits (that can be implemented easily using local storage). 

Users should be able to view the tour again by going to `Help -> Tour`.

**Comment by lorderikir** [comment]
We can implement this in the next version (v0.5.0)

**Comment by lorderikir** [comment]
Walkthrough should use `Bootstrap Tour` instead, easier to use: http://bootstraptour.com/api/

**Comment by lorderikir** [comment]
Wiki documentation has begun, including introduction(s) to MARIE and adding more tutorials as we go along.

**Comment by lorderikir** [comment]
Bootstrap tour test javascript file uploaded...waiting to resolve current issues.

**Comment by lorderikir** [comment]
Fixed in version v0.5.2 in following commits
- 1ef48ec9d48bae84f203913cc3d4f30e9ea7bb07
- b08120dde2cde6956e935f458e66c295606f5a86
