### ISSUE TITLE
Add an icon toolbar

### ISSUE THREAD

**Issue by jos0003** [MARIE-js/MARIE.js#44]
Having an icon toolbar reduces the number of clicks by one for each action, and immediately shows to the user what actions are available to the user.

The disadvantage to this approach is that the icon buttons don't explain what they do. There are a few workarounds to this disadvantage; add tooltips for each icon button, ensure that the icons represent what they do, and follow the conventions (e.g. counter-clockwise arrow for undo action).

Also it would be good if we add icons for the action buttons as well.

**Comment by lorderikir** [comment]
I'm very tempted to put a new library (`fontawesome`) into the website, it has more icons than **glyphicon** , this will introduce new icons that look better.
