### ISSUE TITLE
Proposal for ALU Opcodes

### ISSUE THREAD

**Issue by jos0003** [MARIE-js/MARIE.js#85]
This is a proposal for ALU opcodes which illustrates the purpose of ALUs. In addition to AC and ALU registers, the PC register is also used in the ALU, which is crucial in the fetch part of the fetch-decode-execute cycle.

Here are the opcodes and what they should do:
- `001` - `AC <- AC + MBR`
- `010` - `AC <- AC - MBR`
- `011` - `AC <- 0`
- `100` - `AC < 0?` If so then `PC <- PC + 1`
- `101` - `AC = 0?` If so then `PC <- PC + 1`
- `110` - `AC > 0?` If so then `PC <- PC + 1`
- `111` - `PC <- PC + 1`

**Comment by jos0003** [comment]
Related to #53

**Comment by lorderikir** [comment]
Lecturers agree with this approach, however it is simplifying actual Computer Architecture works. Specifically the comparison between the **AC** and **0** is done by the Control Unit and not the _ALU_ . Also, typically in computer architectures there is a status register which holds several flags such as the _zero flag_.
